PRAGMA foreign_keys = ON;

-- General reusable diagnostic. Assignment is a separate admin action.
INSERT OR IGNORE INTO self_check_tests
  (id, slug, version, title, description, subject, topic, level, estimated_minutes, status)
VALUES (
  'zlomky-zaklady-diagnostika-v1', 'zlomky-zaklady-diagnostika', 1,
  'Zlomky — diagnostický test',
  '[[calculator:Bez kalkulačky]]10 úloh / 20 bodů / přibližně 15–20 minut. Význam zlomku, krácení, rozšiřování, porovnávání, početní operace a propojení s desetinnými čísly. U každé úlohy vyber jednu odpověď. Výsledky uváděj v základním tvaru. Po odeslání uvidíš skóre po oblastech a vysvětlení jednotlivých úloh.',
  'Matematika', 'Zlomky', 'ZŠ / základy SŠ', 20, 'published'
);

INSERT OR IGNORE INTO self_check_questions
  (id, test_id, position, prompt, options_json, correct_answer, explanation, points)
VALUES
  ('zlomky-zaklady-diagnostika-v1-q1',
   'zlomky-zaklady-diagnostika-v1',
   1,
   '{"instruction":"Vyber správný popis zlomku. Celek je rozdělen na stejně velké části.","math":"\\frac{3}{7}","category":"Význam zlomku"}',
   '[{"id":"a","label":"Čitatel je 7, jmenovatel je 3; máme 7 ze 3 stejných částí."},{"id":"b","label":"Čitatel je 3, jmenovatel je 7; máme 3 ze 7 stejných částí."},{"id":"c","label":"Čitatel je 3, jmenovatel je 7; máme 7 ze 3 stejných částí."},{"id":"d","label":"Zlomek znamená 3 + 7 = 10."}]',
   'b',
   'Čitatel je nahoře a udává počet vybraných částí. Jmenovatel je dole a udává, na kolik stejných částí byl celek rozdělen. U 3/7 tedy máme 3 ze 7 stejných částí.',
   2),
  ('zlomky-zaklady-diagnostika-v1-q2',
   'zlomky-zaklady-diagnostika-v1',
   2,
   '{"instruction":"Zkrať zlomek na základní tvar.","math":"\\frac{18}{24}","category":"Krácení a rozšiřování"}',
   '[{"id":"a","label":"[[math:\\frac{9}{12}]]"},{"id":"b","label":"[[math:\\frac{3}{8}]]"},{"id":"c","label":"[[math:\\frac{4}{3}]]"},{"id":"d","label":"[[math:\\frac{3}{4}]]"}]',
   'd',
   'Čitatele i jmenovatele vydělíme šesti: [[math:\frac{18}{24}=\frac{18:6}{24:6}=\frac{3}{4}]]. Zápis 9/12 má stejnou hodnotu, ale ještě není v základním tvaru.',
   2),
  ('zlomky-zaklady-diagnostika-v1-q3',
   'zlomky-zaklady-diagnostika-v1',
   3,
   '{"instruction":"Které číslo patří do prázdného políčka?","math":"\\frac{3}{5}=\\frac{\\square}{20}","category":"Krácení a rozšiřování"}',
   '[{"id":"a","label":"12"},{"id":"b","label":"3"},{"id":"c","label":"18"},{"id":"d","label":"15"}]',
   'a',
   'Jmenovatel 5 násobíme čtyřmi, abychom dostali 20. Stejně násobíme čitatele: 3 · 4 = 12. Hodnota zlomku se tím nezmění.',
   2),
  ('zlomky-zaklady-diagnostika-v1-q4',
   'zlomky-zaklady-diagnostika-v1',
   4,
   '{"instruction":"Doplň správný znak mezi zlomky.","math":"\\frac{2}{3}\\ \\square\\ \\frac{3}{4}","category":"Porovnávání"}',
   '[{"id":"a","label":"[[math:\\frac{2}{3}>\\frac{3}{4}]]"},{"id":"b","label":"[[math:\\frac{2}{3}=\\frac{3}{4}]]"},{"id":"c","label":"[[math:\\frac{2}{3}<\\frac{3}{4}]]"},{"id":"d","label":"Bez kalkulačky to nelze určit."}]',
   'c',
   'Převedeme na společný jmenovatel: [[math:\frac{2}{3}=\frac{8}{12}]] a [[math:\frac{3}{4}=\frac{9}{12}]]. Proto [[math:\frac{2}{3}<\frac{3}{4}]].',
   2),
  ('zlomky-zaklady-diagnostika-v1-q5',
   'zlomky-zaklady-diagnostika-v1',
   5,
   '{"instruction":"Sečti zlomky. Výsledek uveď v základním tvaru.","math":"\\frac{3}{11}+\\frac{5}{11}","category":"Sčítání se stejným jmenovatelem"}',
   '[{"id":"a","label":"[[math:\\frac{8}{22}]]"},{"id":"b","label":"[[math:\\frac{8}{11}]]"},{"id":"c","label":"[[math:\\frac{15}{11}]]"},{"id":"d","label":"[[math:\\frac{2}{11}]]"}]',
   'b',
   'Při stejném jmenovateli sčítáme jen čitatele: [[math:\frac{3}{11}+\frac{5}{11}=\frac{3+5}{11}=\frac{8}{11}]]. Jmenovatele nesčítáme.',
   2),
  ('zlomky-zaklady-diagnostika-v1-q6',
   'zlomky-zaklady-diagnostika-v1',
   6,
   '{"instruction":"Sečti zlomky. Výsledek uveď v základním tvaru.","math":"\\frac{1}{2}+\\frac{1}{4}","category":"Společný jmenovatel"}',
   '[{"id":"a","label":"[[math:\\frac{3}{4}]]"},{"id":"b","label":"[[math:\\frac{1}{3}]]"},{"id":"c","label":"[[math:\\frac{2}{6}]]"},{"id":"d","label":"[[math:\\frac{1}{8}]]"}]',
   'a',
   'Nejprve [[math:\frac{1}{2}=\frac{2}{4}]]. Potom [[math:\frac{2}{4}+\frac{1}{4}=\frac{3}{4}]]. Nelze sčítat čitatele i jmenovatele zároveň.',
   2),
  ('zlomky-zaklady-diagnostika-v1-q7',
   'zlomky-zaklady-diagnostika-v1',
   7,
   '{"instruction":"Odečti zlomky. Výsledek uveď v základním tvaru.","math":"\\frac{5}{6}-\\frac{1}{3}","category":"Společný jmenovatel"}',
   '[{"id":"a","label":"[[math:\\frac{4}{3}]]"},{"id":"b","label":"[[math:\\frac{4}{6}]]"},{"id":"c","label":"[[math:\\frac{2}{9}]]"},{"id":"d","label":"[[math:\\frac{1}{2}]]"}]',
   'd',
   'Rozšíříme druhý zlomek: [[math:\frac{1}{3}=\frac{2}{6}]]. Potom [[math:\frac{5}{6}-\frac{2}{6}=\frac{3}{6}=\frac{1}{2}]]. Odečítáme až po sjednocení jmenovatelů.',
   2),
  ('zlomky-zaklady-diagnostika-v1-q8',
   'zlomky-zaklady-diagnostika-v1',
   8,
   '{"instruction":"Vynásob zlomky. Výsledek uveď v základním tvaru.","math":"\\frac{2}{3}\\cdot\\frac{3}{4}","category":"Násobení"}',
   '[{"id":"a","label":"[[math:\\frac{5}{7}]]"},{"id":"b","label":"[[math:\\frac{6}{12}]]"},{"id":"c","label":"[[math:\\frac{1}{2}]]"},{"id":"d","label":"[[math:\\frac{2}{7}]]"}]',
   'c',
   'Násobíme čitatele mezi sebou a jmenovatele mezi sebou: [[math:\frac{2\cdot3}{3\cdot4}=\frac{6}{12}=\frac{1}{2}]]. Výsledek 6/12 je potřeba ještě zkrátit.',
   2),
  ('zlomky-zaklady-diagnostika-v1-q9',
   'zlomky-zaklady-diagnostika-v1',
   9,
   '{"instruction":"Vyděl zlomky. Výsledek uveď v základním tvaru.","math":"\\frac{3}{5}:\\frac{9}{10}","category":"Dělení"}',
   '[{"id":"a","label":"[[math:\\frac{27}{50}]]"},{"id":"b","label":"[[math:\\frac{2}{3}]]"},{"id":"c","label":"[[math:\\frac{3}{2}]]"},{"id":"d","label":"[[math:\\frac{1}{3}]]"}]',
   'b',
   'Převrátíme pouze druhý zlomek a násobíme: [[math:\frac{3}{5}:\frac{9}{10}=\frac{3}{5}\cdot\frac{10}{9}=\frac{30}{45}=\frac{2}{3}]].',
   2),
  ('zlomky-zaklady-diagnostika-v1-q10',
   'zlomky-zaklady-diagnostika-v1',
   10,
   '{"instruction":"V krabici je 60 bonbonů. Rozdáme tři pětiny všech bonbonů. Vyber dvojici, která správně udává počet rozdaných bonbonů a tento podíl jako desetinné číslo.","math":"\\frac{3}{5}\\ \\text{z}\\ 60","category":"Zlomek z celku a desetinná čísla"}',
   '[{"id":"a","label":"36 bonbonů; podíl 0,6"},{"id":"b","label":"12 bonbonů; podíl 0,6"},{"id":"c","label":"36 bonbonů; podíl 0,35"},{"id":"d","label":"24 bonbonů; podíl 0,4"}]',
   'a',
   'Jedna pětina je 60 : 5 = 12 bonbonů; tři pětiny jsou 3 · 12 = 36 bonbonů. Zároveň [[math:\frac{3}{5}=3:5=0{,}6]]. Rozdáme tedy 36 bonbonů, což je 0,6 původního počtu.',
   2);
