PRAGMA foreign_keys = ON;

-- Reusable digital diagnostic for the existing student self-check engine.
-- Correct answers and explanations remain server-side until submission.
INSERT OR IGNORE INTO self_check_tests
  (id, slug, version, title, description, subject, topic, level, estimated_minutes, status)
VALUES ('algebra-exam-readiness-en-v1', 'algebra-exam-readiness-en', 1, 'Algebra revision — exam readiness self-check', '[[calculator:Bez kalkulačky / no calculator]]15 questions / 25 marks / about 25 minutes. Do this diagnostic before reading the revision PDF. Work independently and choose one answer for every question; use paper for your working. After submission you will see your score by topic, incorrect answers and explanations. Your attempt is saved in your student zone. Nejdříve diagnostika bez nápovědy; PDF je navazující krok 2.', 'Matematika', 'Ratio · Equations · Sequences · Algebra · Quadratics', 'Year 9 / secondary', 25, 'published');

INSERT OR IGNORE INTO self_check_questions
  (id, test_id, position, prompt, options_json, correct_answer, explanation, points)
VALUES
  ('algebra-exam-readiness-en-v1-q1',
   'algebra-exam-readiness-en-v1',
   1,
   '{"instruction":"Simplify the ratio.","math":"45:60","category":"Ratio and Proportion"}',
   '[{"id":"a","label":"9:12"},{"id":"b","label":"3:4"},{"id":"c","label":"4:3"},{"id":"d","label":"15:20"}]',
   'b',
   'Obě části poměru vydělíme 15: 45 : 60 = 3 : 4. Poměry 9 : 12 a 15 : 20 mají stejnou hodnotu, ale nejsou zkrácené na základní tvar.',
   1),
  ('algebra-exam-readiness-en-v1-q2',
   'algebra-exam-readiness-en-v1',
   2,
   '{"instruction":"Divide £96 in the ratio 5:3. Give the amounts in the same order as the ratio.","math":"5:3","category":"Ratio and Proportion"}',
   '[{"id":"a","label":"£48 and £48"},{"id":"b","label":"£36 and £60"},{"id":"c","label":"£60 and £36"},{"id":"d","label":"£64 and £32"}]',
   'c',
   'Poměr má 5 + 3 = 8 dílů. Jeden díl je £96 / 8 = £12. První část je 5 · £12 = £60 a druhá 3 · £12 = £36. Součet je £96.',
   2),
  ('algebra-exam-readiness-en-v1-q3',
   'algebra-exam-readiness-en-v1',
   3,
   '{"instruction":"y is directly proportional to x. When x = 8, y = 20. Find y when x = 14.","math":"y\\propto x","category":"Ratio and Proportion"}',
   '[{"id":"a","label":"[[math:y=35]]"},{"id":"b","label":"[[math:y=26]]"},{"id":"c","label":"[[math:y=5.6]]"},{"id":"d","label":"[[math:y=40]]"}]',
   'a',
   'Přímá úměrnost znamená [[math:y=kx]]. Konstanta je [[math:k=20/8=2.5]], proto [[math:y=2.5\cdot14=35]]. Nejde o přičtení stejného rozdílu k x a y.',
   2),
  ('algebra-exam-readiness-en-v1-q4',
   'algebra-exam-readiness-en-v1',
   4,
   '{"instruction":"Solve the simultaneous equations. Choose the pair that satisfies both equations.","math":"\\begin{cases}x+y=12\\\\x-y=4\\end{cases}","category":"Simultaneous Equations"}',
   '[{"id":"a","label":"[[math:x=6,\\ y=6]]"},{"id":"b","label":"[[math:x=4,\\ y=8]]"},{"id":"c","label":"[[math:x=8,\\ y=-4]]"},{"id":"d","label":"[[math:x=8,\\ y=4]]"}]',
   'd',
   'Sečtením rovnic dostaneme [[math:2x=16]], tedy [[math:x=8]]. Z první rovnice [[math:y=12-8=4]]. Kontrola: 8 + 4 = 12 a 8 − 4 = 4.',
   1),
  ('algebra-exam-readiness-en-v1-q5',
   'algebra-exam-readiness-en-v1',
   5,
   '{"instruction":"Solve the simultaneous equations.","math":"\\begin{cases}3x+2y=19\\\\2x-y=8\\end{cases}","category":"Simultaneous Equations"}',
   '[{"id":"a","label":"[[math:x=2,\\ y=5]]"},{"id":"b","label":"[[math:x=5,\\ y=2]]"},{"id":"c","label":"[[math:x=3,\\ y=5]]"},{"id":"d","label":"[[math:x=5,\\ y=-2]]"}]',
   'b',
   'Druhou rovnici vynásobíme dvěma: [[math:4x-2y=16]]. Po sečtení s první rovnicí vyjde [[math:7x=35]], tedy [[math:x=5]]. Potom [[math:y=2x-8=2]]. Obě rovnice jsou splněné.',
   2),
  ('algebra-exam-readiness-en-v1-q6',
   'algebra-exam-readiness-en-v1',
   6,
   '{"instruction":"Two tickets and one drink cost £17. One ticket and two drinks cost £13. Let t be the price of one ticket and d the price of one drink. Which equations and prices are correct?","math":"t=\\text{ticket price},\\quad d=\\text{drink price}","category":"Simultaneous Equations"}',
   '[{"id":"a","label":"[[math:2t+d=17,\\ t+2d=13]]; ticket £3, drink £7"},{"id":"b","label":"[[math:t+2d=17,\\ 2t+d=13]]; ticket £7, drink £3"},{"id":"c","label":"[[math:2t+d=17,\\ t+2d=13]]; ticket £7, drink £3"},{"id":"d","label":"[[math:2t+d=17,\\ t+2d=13]]; ticket £5, drink £4"}]',
   'c',
   'Dvě vstupenky a nápoj: [[math:2t+d=17]]. Jedna vstupenka a dva nápoje: [[math:t+2d=13]]. Zdvojnásobením druhé a odečtením první vyjde [[math:3d=9]], tedy nápoj £3 a vstupenka £7. Kontrola: 2 · 7 + 3 = 17; 7 + 2 · 3 = 13.',
   2),
  ('algebra-exam-readiness-en-v1-q7',
   'algebra-exam-readiness-en-v1',
   7,
   '{"instruction":"Write the next two terms.","math":"19,\\ 15,\\ 11,\\ 7,\\ldots","category":"Sequences"}',
   '[{"id":"a","label":"3, −1"},{"id":"b","label":"3, 1"},{"id":"c","label":"11, 15"},{"id":"d","label":"−4, −8"}]',
   'a',
   'Rozdíl mezi sousedními členy je vždy −4. Po 7 následuje 7 − 4 = 3 a potom 3 − 4 = −1. Při pokračování přes nulu zůstává stejné pravidlo.',
   1),
  ('algebra-exam-readiness-en-v1-q8',
   'algebra-exam-readiness-en-v1',
   8,
   '{"instruction":"Find the nth term. The first term corresponds to n = 1.","math":"6,\\ 10,\\ 14,\\ 18,\\ldots","category":"Sequences"}',
   '[{"id":"a","label":"[[math:6n+4]]"},{"id":"b","label":"[[math:4n+6]]"},{"id":"c","label":"[[math:4n-2]]"},{"id":"d","label":"[[math:4n+2]]"}]',
   'd',
   'Rozdíl je 4, proto hledáme tvar [[math:4n+b]]. Pro první člen: [[math:4+b=6]], takže [[math:b=2]]. Obecný člen je [[math:u_n=4n+2]]. Pro n = 2 vyjde 10.',
   2),
  ('algebra-exam-readiness-en-v1-q9',
   'algebra-exam-readiness-en-v1',
   9,
   '{"instruction":"The nth term of a sequence is 3n − 2. Which term is equal to 43?","math":"u_n=3n-2","category":"Sequences"}',
   '[{"id":"a","label":"13th term"},{"id":"b","label":"15th term"},{"id":"c","label":"41st term"},{"id":"d","label":"14th term"}]',
   'b',
   'Hledáme pořadí členu, nikoli hodnotu pro n = 43. Položíme [[math:3n-2=43]], tedy [[math:3n=45]] a [[math:n=15]]. Číslo 43 je 15. člen.',
   2),
  ('algebra-exam-readiness-en-v1-q10',
   'algebra-exam-readiness-en-v1',
   10,
   '{"instruction":"Simplify the expression.","math":"8a+3-5a+6","category":"Algebra Recap"}',
   '[{"id":"a","label":"[[math:3a-3]]"},{"id":"b","label":"[[math:13a+9]]"},{"id":"c","label":"[[math:3a+9]]"},{"id":"d","label":"[[math:12a]]"}]',
   'c',
   'Sloučíme členy s a: [[math:8a-5a=3a]]. Čísla sloučíme zvlášť: [[math:3+6=9]]. Výsledek je [[math:3a+9]]; člen s a a samotné číslo nelze sečíst do jednoho členu.',
   1),
  ('algebra-exam-readiness-en-v1-q11',
   'algebra-exam-readiness-en-v1',
   11,
   '{"instruction":"Expand and simplify.","math":"2(3x-4)-3(x+2)","category":"Algebra Recap"}',
   '[{"id":"a","label":"[[math:3x-14]]"},{"id":"b","label":"[[math:3x-2]]"},{"id":"c","label":"[[math:9x-14]]"},{"id":"d","label":"[[math:3x+14]]"}]',
   'a',
   'Roznásobíme obě závorky: [[math:6x-8-3x-6]]. Záporná trojka násobí i +2, proto vzniká −6. Po sloučení vyjde [[math:3x-14]].',
   2),
  ('algebra-exam-readiness-en-v1-q12',
   'algebra-exam-readiness-en-v1',
   12,
   '{"instruction":"Solve the equation.","math":"4x-5=2x+9","category":"Algebra Recap"}',
   '[{"id":"a","label":"[[math:x=2]]"},{"id":"b","label":"[[math:x=-7]]"},{"id":"c","label":"[[math:x=14]]"},{"id":"d","label":"[[math:x=7]]"}]',
   'd',
   'Odečteme 2x z obou stran a přičteme 5: [[math:2x=14]]. Vydělíme dvěma: [[math:x=7]]. Kontrola: 4 · 7 − 5 = 23 a 2 · 7 + 9 = 23.',
   2),
  ('algebra-exam-readiness-en-v1-q13',
   'algebra-exam-readiness-en-v1',
   13,
   '{"instruction":"Factorise the quadratic expression.","math":"x^2+8x+15","category":"Factorising Quadratics"}',
   '[{"id":"a","label":"[[math:(x+1)(x+15)]]"},{"id":"b","label":"[[math:(x+3)(x+5)]]"},{"id":"c","label":"[[math:(x-3)(x-5)]]"},{"id":"d","label":"[[math:(x+2)(x+6)]]"}]',
   'b',
   'Hledáme dvě čísla se součtem 8 a součinem 15: 3 a 5. Proto [[math:x^2+8x+15=(x+3)(x+5)]]. Roznásobením vznikne [[math:x^2+5x+3x+15]].',
   2),
  ('algebra-exam-readiness-en-v1-q14',
   'algebra-exam-readiness-en-v1',
   14,
   '{"instruction":"Factorise the quadratic expression.","math":"x^2-x-12","category":"Factorising Quadratics"}',
   '[{"id":"a","label":"[[math:(x-3)(x+4)]]"},{"id":"b","label":"[[math:(x-4)(x-3)]]"},{"id":"c","label":"[[math:(x-6)(x+2)]]"},{"id":"d","label":"[[math:(x-4)(x+3)]]"}]',
   'd',
   'Součin čísel musí být −12, takže jejich znaménka jsou opačná. Součet musí být −1. Vyhovují −4 a 3: [[math:x^2-x-12=(x-4)(x+3)]]. Pozor: opačné pořadí znamének by dalo +x.',
   2),
  ('algebra-exam-readiness-en-v1-q15',
   'algebra-exam-readiness-en-v1',
   15,
   '{"instruction":"Fully factorise the expression.","math":"3x^2+12x","category":"Factorising Quadratics"}',
   '[{"id":"a","label":"[[math:3(x^2+4x)]]"},{"id":"b","label":"[[math:x(3x+12)]]"},{"id":"c","label":"[[math:3x(x+4)]]"},{"id":"d","label":"[[math:3x(x+12)]]"}]',
   'c',
   'Oba členy mají společný činitel 3x. Vytkneme ho: [[math:3x^2+12x=3x(x+4)]]. Výrazy 3(x² + 4x) a x(3x + 12) jsou správné mezikroky, ale lze z nich ještě vytýkat.',
   1);

-- Explicitly requested assignment to the production-audited Elen account.
-- No other student receives this reusable test automatically.
INSERT OR IGNORE INTO self_check_assignments (id, student_id, test_id, status)
SELECT 'elen-algebra-exam-readiness-en-v1', id,
       'algebra-exam-readiness-en-v1', 'active'
  FROM students
 WHERE id = 'elen' AND display_name = 'Elen' AND enabled = 1;
