#!/usr/bin/env python3
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
from reportlab.platypus import SimpleDocTemplate,Paragraph,Spacer,Table,TableStyle,PageBreak,KeepTogether,HRFlowable
from reportlab.lib.styles import getSampleStyleSheet,ParagraphStyle
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.lib.units import mm
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/'Materials/evelina/2026-08-12__matematika__soustavy-rovnic-3-nezname-matice.pdf'
for n,p in [('DV','/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf'),('DVB','/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf'),('DVI','/usr/share/fonts/truetype/dejavu/DejaVuSans-Oblique.ttf')]: pdfmetrics.registerFont(TTFont(n,p))
NAVY=colors.HexColor('#113E50'); TEAL=colors.HexColor('#17617A'); MID=colors.HexColor('#52636D'); LIGHT=colors.HexColor('#EAF2F6'); LIGHT2=colors.HexColor('#F7F9FA'); LINE=colors.HexColor('#7EA6B8'); TEXT=colors.HexColor('#242C31'); GREEN=colors.HexColor('#356C55')
ss=getSampleStyleSheet(); base=ParagraphStyle('b',parent=ss['BodyText'],fontName='DV',fontSize=10.3,leading=14.2,textColor=TEXT,spaceAfter=4); center=ParagraphStyle('c',parent=base,alignment=TA_CENTER,fontSize=11,leading=15); formula=ParagraphStyle('f',parent=center,fontSize=11.2,leading=17,spaceAfter=5); sec=ParagraphStyle('s',parent=base,fontName='DVB',fontSize=17,leading=21,textColor=NAVY,spaceBefore=7,spaceAfter=4); sub=ParagraphStyle('sub',parent=base,fontName='DVB',fontSize=12.5,leading=16,textColor=TEAL,spaceBefore=6,spaceAfter=3); lab=ParagraphStyle('l',parent=base,fontName='DVB',fontSize=10.1,leading=12.5,textColor=NAVY); ans=ParagraphStyle('a',parent=base,fontName='DVB',textColor=GREEN); t1=ParagraphStyle('t1',parent=base,fontName='DVB',fontSize=14,leading=18,textColor=TEAL,alignment=TA_CENTER,spaceAfter=9); t2=ParagraphStyle('t2',parent=base,fontName='DVB',fontSize=24,leading=29,textColor=NAVY,alignment=TA_CENTER,spaceAfter=7); t3=ParagraphStyle('t3',parent=base,fontName='DVI',fontSize=12,leading=16,textColor=MID,alignment=TA_CENTER,spaceAfter=8)
def P(x,s=base): return Paragraph(x,s)
def H(x): return [P(x,sec),HRFlowable(width='100%',thickness=.65,color=LINE,spaceAfter=8)]
def B(title,body):
 t=Table([[P(title,lab)],[P(body,base)]],colWidths=[174*mm]); t.setStyle(TableStyle([('BACKGROUND',(0,0),(-1,-1),LIGHT),('LEFTPADDING',(0,0),(-1,-1),7),('RIGHTPADDING',(0,0),(-1,-1),7),('TOPPADDING',(0,0),(-1,0),6),('BOTTOMPADDING',(0,0),(-1,0),1),('TOPPADDING',(0,1),(-1,1),0),('BOTTOMPADDING',(0,1),(-1,1),7)])); return t
def M(rows):
 n=len(rows[0]); t=Table([[P(str(v),center) for v in r] for r in rows],colWidths=[14*mm]*(n-1)+[16*mm],hAlign='CENTER'); t.setStyle(TableStyle([('ALIGN',(0,0),(-1,-1),'CENTER'),('LEFTPADDING',(0,0),(-1,-1),4),('RIGHTPADDING',(0,0),(-1,-1),4),('TOPPADDING',(0,0),(-1,-1),3),('BOTTOMPADDING',(0,0),(-1,-1),3),('LINEBEFORE',(n-1,0),(n-1,-1),.8,MID),('LINEBEFORE',(0,0),(0,-1),.8,MID),('LINEAFTER',(-1,0),(-1,-1),.8,MID)])); return t
def footer(c,d):
 c.saveState(); w,h=A4; c.setFillColor(MID); c.setFont('DV',8.2); c.drawRightString(w-18*mm,h-9*mm,'MATEMATIKA | Soustavy rovnic o 3 neznámých'); c.drawRightString(w-18*mm,9*mm,f'Strana {d.page}'); c.restoreState()
st=[Spacer(1,24*mm),P('SOUSTAVY ROVNIC',t1),P('3 neznámé pomocí matice',t2),HRFlowable(width='100%',thickness=.8,color=colors.HexColor('#2D6F8E'),spaceAfter=9),P('Přehledný postup Gaussovy eliminační metody',t3),Spacer(1,3*mm),P('Studijní materiál pro Evelín',ParagraphStyle('e',parent=center,fontSize=11.4,textColor=MID)),Spacer(1,4*mm),B('Cíl materiálu','Převést soustavu tří lineárních rovnic na <b>rozšířenou matici</b>, pomocí řádkových operací vytvořit nuly pod diagonálou a ze vzniklé trojúhelníkové matice určit <b>x, y, z</b>.'),Spacer(1,10*mm),P('Doporučený způsob práce',sub),P('1. Přepiš soustavu do rozšířené matice.',center),P('2. Každou řádkovou operaci proveď i na pravé straně.',center),P('3. Vyráběj nuly pod hlavní diagonálou.',center),P('4. Nakonec řeš soustavu odzadu.',center),PageBreak()]
st+=H('1. Jak převedeme soustavu na matici'); st += [P('Uvažujme soustavu'),P('x + y + z = 6<br/>2x - y + z = 3<br/>x + 2y - z = 2',formula),P('Do rozšířené matice zapisujeme <b>koeficienty před neznámými</b> a pravé strany rovnic:'),M([[1,1,1,6],[2,-1,1,3],[1,2,-1,2]]),Spacer(1,4*mm),B('Co znamenají sloupce?','1. sloupec patří k <b>x</b>, 2. k <b>y</b>, 3. k <b>z</b>. Sloupec za svislou čarou obsahuje pravé strany rovnic.'),Spacer(1,5*mm),P('Chybějící neznámá',sub),P('Pokud některá neznámá v rovnici chybí, její koeficient je <b>0</b>. Například <b>2x - 3z = 5</b> zapíšeme jako:'),M([[2,0,-3,5]]),Spacer(1,4*mm),B('Typická chyba','Nevynechávej nulový koeficient. Jinak se všechny další členy posunou do špatného sloupce.')]
st+=H('2. Povolené řádkové operace'); st += [P('Gaussova eliminace používá tři operace, které nemění řešení soustavy.'),P('<b>1.</b> Prohodit dva řádky: &nbsp; R₁ ↔ R₂'),P('<b>2.</b> Vynásobit celý řádek nenulovým číslem: &nbsp; R₂ ← 3R₂'),P('<b>3.</b> Přičíst násobek jiného řádku: &nbsp; R₂ ← R₂ - 2R₁'),B('Nejdůležitější pravidlo','Operaci musíš provést se <b>všemi prvky řádku</b>, tedy i s číslem napravo od svislé čáry.'),Spacer(1,4*mm),P('Příklad operace R₂ ← R₂ - 2R₁',sub)]
t=Table([[P('R₁',lab),P('(1, 1, 1 | 6)',formula)],[P('R₂',lab),P('(2, -1, 1 | 3)',formula)],[P('2R₁',lab),P('(2, 2, 2 | 12)',formula)],[P('nový R₂',lab),P('(0, -3, -1 | -9)',formula)]],colWidths=[35*mm,115*mm]); t.setStyle(TableStyle([('ROWBACKGROUNDS',(0,0),(-1,-1),[LIGHT2,colors.white]),('LEFTPADDING',(0,0),(-1,-1),6),('RIGHTPADDING',(0,0),(-1,-1),6),('TOPPADDING',(0,0),(-1,-1),4),('BOTTOMPADDING',(0,0),(-1,-1),4)])); st += [t,PageBreak()]
st+=H('3. Vzorový příklad - krok za krokem'); st += [P('Vyřeš soustavu:'),P('x + y + z = 6<br/>2x - y + z = 3<br/>x + 2y - z = 2',formula),P('Výchozí matice',sub),M([[1,1,1,6],[2,-1,1,3],[1,2,-1,2]]),Spacer(1,3*mm),P('<b>Krok 1:</b> vytvoříme nuly pod první jedničkou.'),P('R₂ ← R₂ - 2R₁ &nbsp;&nbsp;&nbsp; R₃ ← R₃ - R₁',formula),M([[1,1,1,6],[0,-3,-1,-9],[0,1,-2,-4]]),Spacer(1,3*mm),P('<b>Krok 2:</b> prohodíme R₂ a R₃, abychom měli jednoduchý pivot 1.'),P('R₂ ↔ R₃',formula),M([[1,1,1,6],[0,1,-2,-4],[0,-3,-1,-9]]),Spacer(1,3*mm),P('<b>Krok 3:</b> vytvoříme nulu pod druhým pivotem.'),P('R₃ ← R₃ + 3R₂',formula),M([[1,1,1,6],[0,1,-2,-4],[0,0,-7,-21]]),Spacer(1,4*mm),B('Máme trojúhelníkový tvar','Pod hlavní diagonálou jsou nuly. Teď už jen provedeme <b>zpětné dosazení</b>.'),Spacer(1,4*mm),P('3. řádek: -7z = -21 → <b>z = 3</b>'),P('2. řádek: y - 2z = -4 → y - 6 = -4 → <b>y = 2</b>'),P('1. řádek: x + y + z = 6 → x + 2 + 3 = 6 → <b>x = 1</b>'),P('Řešení: [x, y, z] = [1, 2, 3]',ans)]
st+=H('4. Zvláštní poslední řádky'); st += [P('Při eliminaci může poslední řádek okamžitě rozhodnout o počtu řešení.'),P('Případ A: 0 = 5',sub),M([[0,0,0,5]]),P('Vznikl spor → soustava <b>nemá řešení</b>.'),P('Případ B: 0 = 0',sub),M([[0,0,0,0]]),P('Řádek nepřidává novou informaci. Pokud není nikde spor, soustava může mít <b>nekonečně mnoho řešení</b>.'),B('Rychlé rozhodnutí','<b>0 = nenulové číslo → žádné řešení.</b><br/><b>0 = 0 → závislý řádek; typicky nekonečně mnoho řešení.</b>'),PageBreak()]
st+=H('5. Praktický algoritmus do písemky'); steps=['Přepiš soustavu do rozšířené matice.','Najdi vhodný pivot v prvním sloupci.','Vytvoř nuly pod pivotem.','Přejdi do druhého sloupce a znovu vytvoř nulu pod pivotem.','Jakmile máš trojúhelníkový tvar, eliminaci zastav.','Urči z, potom y a nakonec x.','Výsledek krátce zkontroluj v původní soustavě.']; t=Table([[P(str(i+1),center),P(s)] for i,s in enumerate(steps)],colWidths=[12*mm,150*mm]); t.setStyle(TableStyle([('ROWBACKGROUNDS',(0,0),(-1,-1),[LIGHT2,colors.white]),('LEFTPADDING',(0,0),(-1,-1),6),('RIGHTPADDING',(0,0),(-1,-1),6),('TOPPADDING',(0,0),(-1,-1),5),('BOTTOMPADDING',(0,0),(-1,-1),5)])); st += [t,Spacer(1,5*mm),B('Co si hlídat','Nejčastější chyby jsou ve <b>znaménkách</b>, v zapomenuté pravé straně řádku a v příliš složitých operacích. Když můžeš, vybírej pivot 1 nebo -1.')]
st+=H('6. Cvičení'); ex=[('A1','x + y + z = 6<br/>2x - y + z = 3<br/>x + 2y - z = 2'),('A2','x + y + z = 3<br/>2x - y + z = 3<br/>x + 3y - 2z = 5'),('A3','x + y + z = 4<br/>2x - y + z = -1<br/>3x + 2y - z = -2'),('A4','2x + y - z = -2<br/>x - y + 2z = 7<br/>3x + 2y + z = 1'),('A5','x + 2y - z = 2<br/>2x + 4y - 2z = 4<br/>x - y + z = 1'),('A6','x + y + z = 1<br/>2x + 2y + 2z = 3<br/>x - y + z = 0')]
for code,eqs in ex: st.append(KeepTogether([P(f'<b>{code}</b> Vyřeš soustavu pomocí rozšířené matice.'),P(eqs,formula),Spacer(1,2*mm)]))
st += [B('Doporučení k tréninku','U A1-A4 napiš celý maticový postup. U A5-A6 se soustřeď hlavně na význam posledního řádku po eliminaci.'),PageBreak()]
st+=H('7. Výsledky a rychlý tahák'); st += [P('<b>A1:</b> x = 1, y = 2, z = 3',ans),P('<b>A2:</b> x = 2, y = 1, z = 0',ans),P('<b>A3:</b> x = -1, y = 2, z = 3',ans),P('<b>A4:</b> x = 1, y = -2, z = 2',ans),P('<b>A5:</b> nekonečně mnoho řešení',ans),P('<b>A6:</b> soustava nemá řešení',ans),Spacer(1,8*mm),P('Tahák: co chci z matice dostat',sub),M([['a','b','c','d'],[0,'e','f','g'],[0,0,'h','i']]),Spacer(1,5*mm),P('Jakmile má matice tento tvar, řeš odspodu:'),P('h·z = i → z &nbsp;&nbsp; | &nbsp;&nbsp; e·y + f·z = g → y &nbsp;&nbsp; | &nbsp;&nbsp; a·x + b·y + c·z = d → x',formula),Spacer(1,6*mm),B('Jedna věta, kterou si zapamatuj','<b>Gaussova eliminace = pomocí řádkových operací vyrábím nuly pod diagonálou a potom řeším soustavu odzadu.</b>')]
OUT.parent.mkdir(parents=True,exist_ok=True); SimpleDocTemplate(str(OUT),pagesize=A4,leftMargin=18*mm,rightMargin=18*mm,topMargin=20*mm,bottomMargin=18*mm).build(st,onFirstPage=footer,onLaterPages=footer)
print(OUT)
